import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/Component/Footer";
import Header from "@/Component/Header";



export const metadata: Metadata = {
  title: "MERN STACK App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
